"""Generate a minimal x64 .vcxproj using build/TwProject.props and register it in TacticalWar.sln.

Usage (from the repository root):
    py tools/vsproj/new_project.py <Name> <lib|exe> [--ref Project ...] [--libs a.lib;b.lib]

Source files (*.h, *.cpp) found in <Name>/ (recursively) are listed in the project.
Re-running the script regenerates the .vcxproj (keeping its GUID) so new files are picked up.
"""
import argparse
import os
import re
import uuid

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SLN = os.path.join(ROOT, 'TacticalWar.sln')
VCPP_TYPE = '{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}'


def find_guid(vcxproj_path):
    text = open(vcxproj_path, encoding='utf-8-sig').read()
    return re.search(r'<ProjectGuid>(\{[^}]+\})</ProjectGuid>', text).group(1).upper()


def sources(project_dir):
    headers, cpps = [], []
    for root, dirs, files in os.walk(project_dir):
        dirs[:] = [d for d in dirs if d not in ('x64', 'Debug', 'Release')]
        for f in sorted(files):
            rel = os.path.relpath(os.path.join(root, f), project_dir)
            if f.endswith(('.h', '.hpp')):
                headers.append(rel)
            elif f.endswith('.cpp'):
                cpps.append(rel)
    return sorted(headers), sorted(cpps)


def generate(name, kind, refs, libs):
    project_dir = os.path.join(ROOT, name)
    path = os.path.join(project_dir, name + '.vcxproj')
    guid = find_guid(path) if os.path.exists(path) else '{' + str(uuid.uuid4()).upper() + '}'
    headers, cpps = sources(project_dir)
    config_type = 'StaticLibrary' if kind == 'lib' else 'Application'

    ref_items = []
    for ref in refs:
        ref_path = os.path.join(ROOT, ref, ref + '.vcxproj')
        ref_items.append(
            f'    <ProjectReference Include="..\\{ref}\\{ref}.vcxproj">\n'
            f'      <Project>{find_guid(ref_path).lower()}</Project>\n'
            f'    </ProjectReference>')

    link = ''
    if kind == 'exe':
        deps = (libs + ';' if libs else '') + '%(AdditionalDependencies)'
        link = ('  <ItemDefinitionGroup>\n    <Link>\n      <SubSystem>Console</SubSystem>\n'
                f'      <AdditionalDependencies>{deps}</AdditionalDependencies>\n    </Link>\n  </ItemDefinitionGroup>\n')

    configs = ''.join(
        f'    <ProjectConfiguration Include="{c}|x64">\n      <Configuration>{c}</Configuration>\n'
        f'      <Platform>x64</Platform>\n    </ProjectConfiguration>\n' for c in ('Debug', 'Release'))

    xml = f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/vsproj/new_project.py: re-run it after adding source files. -->
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Label="ProjectConfigurations">
{configs}  </ItemGroup>
  <PropertyGroup Label="Globals">
    <VCProjectVersion>17.0</VCProjectVersion>
    <ProjectGuid>{guid}</ProjectGuid>
    <Keyword>Win32Proj</Keyword>
    <RootNamespace>{name}</RootNamespace>
    <WindowsTargetPlatformVersion>10.0.26100.0</WindowsTargetPlatformVersion>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.Default.props" />
  <PropertyGroup Label="Configuration">
    <ConfigurationType>{config_type}</ConfigurationType>
    <PlatformToolset>v143</PlatformToolset>
    <CharacterSet>Unicode</CharacterSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'" Label="Configuration">
    <UseDebugLibraries>true</UseDebugLibraries>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'" Label="Configuration">
    <UseDebugLibraries>false</UseDebugLibraries>
    <WholeProgramOptimization>true</WholeProgramOptimization>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.props" />
  <ImportGroup Label="PropertySheets">
    <Import Project="$(TwRootDir)build\\TwProject.props" />
  </ImportGroup>
{link}  <ItemGroup>
{chr(10).join(f'    <ClInclude Include="{h}" />' for h in headers)}
  </ItemGroup>
  <ItemGroup>
{chr(10).join(f'    <ClCompile Include="{c}" />' for c in cpps)}
  </ItemGroup>
  <ItemGroup>
{chr(10).join(ref_items)}
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.targets" />
</Project>
'''
    with open(path, 'w', encoding='utf-8', newline='\r\n') as f:
        f.write(xml)
    register_in_sln(name, guid)
    print(f'{path} ({guid}): {len(headers)} headers, {len(cpps)} sources')


def register_in_sln(name, guid):
    raw = open(SLN, 'rb').read()
    bom = raw.startswith(b'\xef\xbb\xbf')
    text = raw.decode('utf-8-sig').replace('\r\n', '\n')
    if guid in text.upper():
        return
    project = f'Project("{VCPP_TYPE}") = "{name}", "{name}\\{name}.vcxproj", "{guid}"\nEndProject\n'
    text = text.replace('\nGlobal\n', '\n' + project + 'Global\n', 1)
    lines = []
    for sol_cfg in ('Debug|Any CPU', 'Debug|x64', 'Debug|x86', 'Release|Any CPU', 'Release|x64', 'Release|x86'):
        conf = sol_cfg.split('|')[0]
        lines.append(f'\t\t{guid}.{sol_cfg}.ActiveCfg = {conf}|x64')
        if sol_cfg.endswith('x64'):
            lines.append(f'\t\t{guid}.{sol_cfg}.Build.0 = {conf}|x64')
    marker = '\tGlobalSection(ProjectConfigurationPlatforms) = postSolution\n'
    start = text.index(marker) + len(marker)
    end = text.index('\tEndGlobalSection\n', start)
    text = text[:end] + '\n'.join(lines) + '\n' + text[end:]
    data = text.replace('\n', '\r\n').encode('utf-8')
    open(SLN, 'wb').write((b'\xef\xbb\xbf' if bom else b'') + data)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('name')
    parser.add_argument('kind', choices=['lib', 'exe'])
    parser.add_argument('--ref', action='append', default=[])
    parser.add_argument('--libs', default='')
    args = parser.parse_args()
    generate(args.name, args.kind, args.ref, args.libs)
