name: Compilation et tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - uses: microsoft/setup-msbuild@v2

      - name: Compilation (Release x64)
        run: msbuild TacticalWar.sln -p:Configuration=Release -p:Platform=x64 -m -v:minimal -nologo

      - name: Tests unitaires
        working-directory: x64/Release
        run: .\TacticalWarTests.exe
